[package]
name = "d1"
version = "0.1.0"
edition = "2021"

[dependencies]
worker = { version="0.5.0", features=['http', 'd1'] }
anyhow = "1.0.95"
serde = "1.0.217"
reqwest = { version = "0.12.12", features = ["json"] }
chrono = "0.4.39"
serde_json = "1.0.138"