[package]
edition = "2021"
name = "open-class-discord"
version = "0.1.0"

[lib]
name = "workers"
crate-type = ["cdylib"]
path = "/workers/src/lib.rs"

[workspace]
members = [
    "bin/register-commands",
    "workers",
    "crates/*"
]
default-members = []
resolver = "2"
