[package]
name = "register-commands"
version = "0.1.0"
edition = "2021"

[dependencies]
discord = { path = "../../crates/discord" }
anyhow = "1.0.95"
reqwest = { version = "0.12.12", features = ["json"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
dotenv = "0.15.0"